-- Crear tabla Line
CREATE TABLE LineVW (
    idLine NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    lineName VARCHAR2(100) NOT NULL,
);

-- SP para agregar una linea
CREATE OR REPLACE PROCEDURE ADDLINE(
    lineName IN VARCHAR2
) AS 
BEGIN
    INSERT INTO LineVW(
        lineName
    ) VALUES (
        lineName
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ADDLINE;

-- Insertar lineas
BEGIN
    EXECUTE ADDLINE('Línea Cigueñal');
    EXECUTE ADDLINE('Línea Monoblock');
    EXECUTE ADDLINE('Línea Piston');
END;

-- Crear tabla Cell
CREATE TABLE Cell (
    idCell NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cellName VARCHAR2(100) NOT NULL,
    idUser NUMBER,
    idLine NUMBER
);

-- SP para agregar una celula
CREATE OR REPLACE PROCEDURE ADDCELL(
    cellName IN VARCHAR2,
    idUser IN NUMBER,
    idLine IN NUMBER
) AS
BEGIN
    INSERT INTO Cell(
        cellName,
        idUser,
        idLine
    ) VALUES (
        cellName,
        idUser,
        idLine
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ADDCELL;

-- Insertar celulas
BEGIN
    EXECUTE ADDCELL('Célula A', 1, 1); -- Aquí se asumen valores de idUser y idLine
    EXECUTE ADDCELL('Célula B', 2, 2); -- que corresponden a registros existentes
    EXECUTE ADDCELL('Célula C', 3, 3); -- en las tablas de usuarios y líneas
END;