--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OBJECTIVESINDICATORS
--------------------------------------------------------

  CREATE TABLE "UANDARI_USER"."OBJECTIVESINDICATORS" 
   (	"IDOBJECTIVESINDICATORS" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDUSER" NUMBER, 
	"SECURITY_MUST" NUMBER, 
	"PRODUCTIONVOLUME_MUST" NUMBER, 
	"ISSUESB_MUST" NUMBER, 
	"ISSUESC1_MUST" NUMBER, 
	"DAMAGEDMATERIAL_MUST" NUMBER, 
	"ISDELETE" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UANDARI_USER.OBJECTIVESINDICATORS
SET DEFINE OFF;
Insert into UANDARI_USER.OBJECTIVESINDICATORS (IDOBJECTIVESINDICATORS,IDUSER,SECURITY_MUST,PRODUCTIONVOLUME_MUST,ISSUESB_MUST,ISSUESC1_MUST,DAMAGEDMATERIAL_MUST,ISDELETE) values (1,1,10,20,30,40,50,0);
Insert into UANDARI_USER.OBJECTIVESINDICATORS (IDOBJECTIVESINDICATORS,IDUSER,SECURITY_MUST,PRODUCTIONVOLUME_MUST,ISSUESB_MUST,ISSUESC1_MUST,DAMAGEDMATERIAL_MUST,ISDELETE) values (2,2,15,25,35,45,55,0);
Insert into UANDARI_USER.OBJECTIVESINDICATORS (IDOBJECTIVESINDICATORS,IDUSER,SECURITY_MUST,PRODUCTIONVOLUME_MUST,ISSUESB_MUST,ISSUESC1_MUST,DAMAGEDMATERIAL_MUST,ISDELETE) values (3,3,5,15,25,35,45,0);
Insert into UANDARI_USER.OBJECTIVESINDICATORS (IDOBJECTIVESINDICATORS,IDUSER,SECURITY_MUST,PRODUCTIONVOLUME_MUST,ISSUESB_MUST,ISSUESC1_MUST,DAMAGEDMATERIAL_MUST,ISDELETE) values (4,4,8,18,28,38,48,0);
Insert into UANDARI_USER.OBJECTIVESINDICATORS (IDOBJECTIVESINDICATORS,IDUSER,SECURITY_MUST,PRODUCTIONVOLUME_MUST,ISSUESB_MUST,ISSUESC1_MUST,DAMAGEDMATERIAL_MUST,ISDELETE) values (5,5,12,22,32,42,52,0);
--------------------------------------------------------
--  DDL for Index PK_IDOBJECTIVESINDICATORS
--------------------------------------------------------

  CREATE UNIQUE INDEX "UANDARI_USER"."PK_IDOBJECTIVESINDICATORS" ON "UANDARI_USER"."OBJECTIVESINDICATORS" ("IDOBJECTIVESINDICATORS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table OBJECTIVESINDICATORS
--------------------------------------------------------

  ALTER TABLE "UANDARI_USER"."OBJECTIVESINDICATORS" MODIFY ("IDOBJECTIVESINDICATORS" NOT NULL ENABLE);
  ALTER TABLE "UANDARI_USER"."OBJECTIVESINDICATORS" ADD CONSTRAINT "PK_IDOBJECTIVESINDICATORS" PRIMARY KEY ("IDOBJECTIVESINDICATORS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
