--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TECHNICIANS
--------------------------------------------------------

  CREATE TABLE "UANDARI_USER"."TECHNICIANS" 
   (	"IDTECHNICIAN" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDOPERATION" NUMBER, 
	"IDCELL" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"CONTROLNUMBER" VARCHAR2(255 BYTE), 
	"POSITION" VARCHAR2(255 BYTE), 
	"REALPOSITION" VARCHAR2(255 BYTE), 
	"LASTNAMES" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UANDARI_USER.TECHNICIANS
SET DEFINE OFF;
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (1,1,2,'Nombre1','Control1','Posición1','RealPosición1',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (2,2,81,'Nombre2','Control2','Posición2','RealPosición2',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (3,3,82,'Nombre3','Control3','Posición3','RealPosición3',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (4,4,1,'Nombre4','Control4','Posición4','RealPosición4',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (5,5,42,'Nombre5','Control5','Posición5','RealPosición5',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (6,6,43,'Nombre6','Control6','Posición6','RealPosición6',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (7,7,61,'Nombre7','Control7','Posición7','RealPosición7',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (8,8,21,'Nombre8','Control8','Posición8','RealPosición8',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (9,9,3,'Nombre9','Control9','Posición9','RealPosición9',null);
Insert into UANDARI_USER.TECHNICIANS (IDTECHNICIAN,IDOPERATION,IDCELL,NAME,CONTROLNUMBER,POSITION,REALPOSITION,LASTNAMES) values (10,10,2,'Nombre10','Control10','Posición10','RealPosición10',null);
--------------------------------------------------------
--  DDL for Index SYS_C008370
--------------------------------------------------------

  CREATE UNIQUE INDEX "UANDARI_USER"."SYS_C008370" ON "UANDARI_USER"."TECHNICIANS" ("IDTECHNICIAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TECHNICIANS
--------------------------------------------------------

  ALTER TABLE "UANDARI_USER"."TECHNICIANS" MODIFY ("IDTECHNICIAN" NOT NULL ENABLE);
  ALTER TABLE "UANDARI_USER"."TECHNICIANS" ADD PRIMARY KEY ("IDTECHNICIAN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-27-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View COMPLETETECHNICIANS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "UANDARI_USER"."COMPLETETECHNICIANS" ("IDTECHNICIAN", "NAME", "LASTNAMES", "CONTROLNUMBER", "LINENAME", "OPERATIONNAME", "POSITION", "REALPOSITION") AS 
  SELECT
    T.idTechnician,
    T.name,
    T.lastNames,
    T.controlNumber,
    L.lineName AS LineName,
    O.name_ AS OperationName,
    T.position,
    T.realPosition
FROM
    TECHNICIANS T
LEFT JOIN
    OPERATION O ON T.idOperation = O.idOperation
LEFT JOIN
    Cell C ON T.idCell = C.idCell
LEFT JOIN
    LineVW L ON C.idLine = L.idLine
;
REM INSERTING into UANDARI_USER.COMPLETETECHNICIANS
SET DEFINE OFF;
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (4,'Nombre4',null,'Control4','Línea Cigueñal','1560','Posición4','RealPosición4');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (1,'Nombre1',null,'Control1','Línea Cigueñal','0','Posición1','RealPosición1');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (10,'Nombre10',null,'Control10','Línea Cigueñal','350','Posición10','RealPosición10');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (5,'Nombre5',null,'Control5','Línea Cigueñal','180','Posición5','RealPosición5');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (6,'Nombre6',null,'Control6','Línea Cigueñal','930','Posición6','RealPosición6');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (7,'Nombre7',null,'Control7','Línea Cigueñal','1210','Posición7','RealPosición7');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (9,'Nombre9',null,'Control9','Línea Piston','0','Posición9','RealPosición9');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (8,'Nombre8',null,'Control8',null,'720','Posición8','RealPosición8');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (2,'Nombre2',null,'Control2',null,'350','Posición2','RealPosición2');
Insert into UANDARI_USER.COMPLETETECHNICIANS (IDTECHNICIAN,NAME,LASTNAMES,CONTROLNUMBER,LINENAME,OPERATIONNAME,POSITION,REALPOSITION) values (3,'Nombre3',null,'Control3',null,'0','Posición3','RealPosición3');
