export enum USER_PROCEDURES {
  GET_USERS = "SELECT * FROM USERVW",
  CREATE_USER = "ADDUSER",
  UPDATE_USER = "UPDATEUSER",
  DELETE_USER = "DELETEUSER",
  LOGIN_USER = "LOGINUSER",
  GETBYCONTROLNUMBER = "SELECT * FROM USERVW WHERE idUser = ",
}
export enum ROLE_PROCEDURES {
  GET_ROLES = "SELECT * FROM  ROLE",
  CREATE_ROLE = "ADDROLE",
  UPDATE_ROLE = "UPDATEROLE",
  DELETE_ROLE = "DELETEROLE",
  GETBYID = "SELECT * FROM ROLE WHERE idRole = ",
}
export enum HOURXHOUR_PROCEDURES {
  INSERT_MUST_AND_GET_ID = "BEGIN InsertMustAndGetID(:p_must, :p_id); END;",
  UPDATE_HOURXHOUR = "UPDATEHOURXHOUR",
  GETBYID = "SELECT * FROM HourxHour WHERE idHourXHour = ",
}

export enum ISSUE_PROCEDURES {
  GET_ISSUES = "SELECT * FROM ISSUEVW",
  INSERT_ISSUE = "ADDISSUE",
}
